// Code generated by mockery v2.43.2. DO NOT EDIT.

package controller

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockControllerAPI is an autogenerated mock type for the ControllerAPI type
type MockControllerAPI struct {
	mock.Mock
}

// GracefulShutdown provides a mock function with given fields:
func (_m *MockControllerAPI) GracefulShutdown() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GracefulShutdown")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HandleBatch provides a mock function with given fields: ctx
func (_m *MockControllerAPI) HandleBatch(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for HandleBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockControllerAPI creates a new instance of MockControllerAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockControllerAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockControllerAPI {
	mock := &MockControllerAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
