// Code generated by mockery v2.43.2. DO NOT EDIT.

package service

import (
	request "aculo/connector-restapi/internal/request"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// SendEvent provides a mock function with given fields: ctx, req
func (_m *MockService) SendEvent(ctx context.Context, req request.SendEventRequest) (request.SendEventResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SendEvent")
	}

	var r0 request.SendEventResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, request.SendEventRequest) (request.SendEventResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, request.SendEventRequest) request.SendEventResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(request.SendEventResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, request.SendEventRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
