Logger:
    SyncTimeout: 1s 
    Cores:
      - Name : stderr
        EncoderLevel: production
        Path: /dev/stderr
        Level : 0 # info
        MustCreateCore: false
      - Name : logfile
        EncoderLevel: production
        Path: "${WORKSPACE}/tmp/log.log"
        Level : -1 # debug
        MustCreateCore: true
Controller:
  GRPCServer:
    Address: "localhost:7731"
  HTTPServer:
    Address: "localhost:7730"
#Broker:
#    Addresses:
#      - localhost:9092
#      - localhost:9093
#    BatchSize: 1000
#    Offset: -1 # sarama.OffsetNewest
#    Topic: "test"
#    BatchProvider:
#      PreallocSize: 20