// Code generated by mockery v2.43.2. DO NOT EDIT.

package testutils

import mock "github.com/stretchr/testify/mock"

// MockTestutils is an autogenerated mock type for the Testutils type
type MockTestutils struct {
	mock.Mock
}

// NewMockTestutils creates a new instance of MockTestutils. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTestutils(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTestutils {
	mock := &MockTestutils{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
