Logger:
    SyncTimeout: 1s 
    Cores:
      - Name : stderr
        EncoderLevel: production
        Path: /dev/stderr
        Level : 0 # info
        MustCreateCore: false
      - Name : logfile
        EncoderLevel: production
        Path: "${WORKSPACE}/tmp/log.log"
        Level : -1 # debug
        MustCreateCore: true
Broker:
    Addresses:
      - kafka0:29094
      - kafka1:29094
    BatchSize: 1000
    Topic: "test"
    BatchProvider:
      PreallocSize: 20
Repository:
  Addresses: 
    - "clickhouse:9000"
