FROM golang:1.22.5-alpine3.20 AS builder
ARG DOCKER_WORKDIR=/app
ARG APP

WORKDIR ${DOCKER_WORKDIR}
COPY . .
RUN apk add bash 
# Change make on appmanager.sh run 
RUN bash -c "./appmanager.sh build"

# FROM debian:bookworm AS runner
FROM alpine:3.20 AS runner
WORKDIR ${DOCKER_WORKDIR}

COPY --from=builder /${DOCKER_WORKDIR}/bin/${APP} ./bin/
COPY --from=builder /${DOCKER_WORKDIR}/appmanager.sh ./
# Change make on appmanager.sh run 
RUN apk add bash 
# Change make on appmanager.sh run 
CMD bash -c "./appmanager.sh run"   