// Code generated by mockery v2.43.2. DO NOT EDIT.

package repository

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockEventRepository is an autogenerated mock type for the EventRepository type
type MockEventRepository struct {
	mock.Mock
}

// GetEvent provides a mock function with given fields: _a0, _a1
func (_m *MockEventRepository) GetEvent(_a0 context.Context, _a1 GetEventRequest) (GetEventResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetEvent")
	}

	var r0 GetEventResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, GetEventRequest) (GetEventResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, GetEventRequest) GetEventResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(GetEventResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, GetEventRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockEventRepository creates a new instance of MockEventRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventRepository {
	mock := &MockEventRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
