// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.28.1
// source: api/controller.proto

package grpcctl

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RegistratorClient is the client API for Registrator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegistratorClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
}

type registratorClient struct {
	cc grpc.ClientConnInterface
}

func NewRegistratorClient(cc grpc.ClientConnInterface) RegistratorClient {
	return &registratorClient{cc}
}

func (c *registratorClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/Registrator/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistratorServer is the server API for Registrator service.
// All implementations must embed UnimplementedRegistratorServer
// for forward compatibility
type RegistratorServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	mustEmbedUnimplementedRegistratorServer()
}

// UnimplementedRegistratorServer must be embedded to have forward compatible implementations.
type UnimplementedRegistratorServer struct {
}

func (UnimplementedRegistratorServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedRegistratorServer) mustEmbedUnimplementedRegistratorServer() {}

// UnsafeRegistratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegistratorServer will
// result in compilation errors.
type UnsafeRegistratorServer interface {
	mustEmbedUnimplementedRegistratorServer()
}

func RegisterRegistratorServer(s grpc.ServiceRegistrar, srv RegistratorServer) {
	s.RegisterService(&Registrator_ServiceDesc, srv)
}

func _Registrator_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistratorServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Registrator/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistratorServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Registrator_ServiceDesc is the grpc.ServiceDesc for Registrator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Registrator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Registrator",
	HandlerType: (*RegistratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Registrator_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/controller.proto",
}
