FROM golang:1.22.5-alpine3.20 AS builder

ARG DOCKER_WORKDIR=/app
ARG APP

WORKDIR ${DOCKER_WORKDIR}
COPY . .
RUN apk add bash 

ENV WORKSPACE=${DOCKER_WORKDIR}

RUN bash -c " ./aculo-manager.sh build"

FROM alpine:3.20 AS runner

ARG DOCKER_WORKDIR=/app
ARG APP

WORKDIR ${DOCKER_WORKDIR}


COPY --from=builder ${DOCKER_WORKDIR}/bin/${APP} ./bin/
COPY --from=builder ${DOCKER_WORKDIR}/aculo-manager.sh .

RUN apk add bash 

ENV APP ${APP}

CMD bash -c "./aculo-manager.sh run"   