FROM golang:1.22.5-alpine3.20 AS builder

WORKDIR /app

COPY . .

RUN apk add bash 

RUN bash -c "./aculo-manager.sh build"

FROM alpine:3.20 AS runner
WORKDIR /app

COPY --from=builder /app/bin/connector-rest ./bin/
COPY --from=builder /app/aculo-manager.sh ./

RUN apk add bash 

CMD bash -c "./aculo-manager.sh run"   