basePath: /api/v1
definitions:
  event.Error:
    properties:
      status:
        type: string
    type: object
  event.Rsp200:
    properties:
      status:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /event/:
    post:
      consumes:
      - application/json
      description: Least preferable variant, but still works
      parameters:
      - description: Raw event to send
        in: body
        name: event
        required: true
        schema:
          type: string
      - description: Topic to send event
        in: query
        name: topic
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/event.Rsp200'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/event.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/event.Error'
      summary: Send single event via REST
      tags:
      - events
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
